AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'

Metrics/LineLength:
  Max: 120

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
